# MOVE CODES
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3
DO_NOTHING = 4

# TILES CODES
GRASS = 0
LAVA = 1
BERRY = 2
KAT = 3
WALL  = 4

# NUMBER OF PURE CLONES WITHIN A GENERATION
AMT_CLONE = 5

# AMOUNT OF TRIALS TO FIND BEST KAT
NUM_OF_TRIALS = 50 # Should be divisible by 5

# NUMBER OF GENERATIONS
NUM_SIMS = 20

# MAXIMUM STEPS PER SIMULATION
STEPS_PER_SIM = 300

# KAT'S VISION RANGE
VISION_RANGE = 2

# FIXED MAP FEATURES
WALLS_OF_DEATH  = False  # Walls are lava
WALL_PILLARS    = False  # Wall tiles periodically jut out
MAZE            = False
